---
#
# IMPORTANT:
#   * Only Ubuntu 16.04 [Xenial] is supported at the moment (although it might work on Ubuntu 18.04 [bionic])
#   * certbot is expected to install a systemd timer to handle renewals
#
- name: Install base packages.
  package:
    name:
      - software-properties-common
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    state: latest

- name: Add Universe repository.
  command: add-apt-repository universe
  become: true

- name: Add Certbot repository.
  apt_repository:
    repo: ppa:certbot/certbot

- name: Create Certbot base directory
  file:
    path: "{{ certbot_base_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

#
# IMPORTANT:
#   * Only nginx is supported at the moment
#   * Only AWS Route 53 is supported at the moment
#
- name: Install Certbot.
  package:
    name:
      - certbot
      # - python-certbot-nginx
      - python3-certbot-dns-route53
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
    state: latest
